/* eslint-disable */
/**
 * 本文件由 vendor-api/pixmax/models.json 生成（生图与生视频模型），用于按模型规格组装 PixMax 任务参数。
 * PixMax 新增或调整模型后重新生成；模型是否可用以 `POST /openapi/model/available` 为准。
 */
import type { PixmaxModelSpec } from './pixmax.entity.js';

/**
 * @description PixMax 生图 / 生视频模型规格目录（参数默认值、可选值、时长范围、生成模式与输入上限）。
 * @keyword-cn PixMax模型规格, 参数目录
 * @keyword-en pixmax-model-spec, param-catalog
 */
export const PIXMAX_MODEL_CATALOG: readonly PixmaxModelSpec[] = [
  {
    code: 'PixImage_2.5_Flare',
    name: 'PixImage 2.5 Flare',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 16,
    },
    params: [
      {
        name: 'quality',
        type: 'string',
        defaultValue: 'medium',
        options: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '1K',
        options: ['1K', '2K', '4K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '1:1',
        options: [
          '1:1',
          '1:3',
          '3:1',
          '3:2',
          '2:3',
          '4:3',
          '3:4',
          '4:5',
          '5:4',
          '16:9',
          '9:16',
          '21:9',
          '9:21',
        ],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'PixImage_2.5_Sunburst',
    name: 'PixImage 2.5 Sunburst',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 16,
    },
    params: [
      {
        name: 'quality',
        type: 'string',
        defaultValue: 'medium',
        options: ['low', 'medium', 'high', 'xhigh', 'max'],
      },
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '1K',
        options: ['1K', '2K', '4K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '1:1',
        options: [
          '1:1',
          '1:3',
          '3:1',
          '3:2',
          '2:3',
          '4:3',
          '3:4',
          '4:5',
          '5:4',
          '16:9',
          '9:16',
          '21:9',
          '9:21',
        ],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'DOUBAO_SEEDREAM_5_PRO',
    name: 'Doubao Seedream 5.0 Pro',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 10,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '2K',
        options: ['1K', '2K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '1:1',
        options: ['1:1', '2:3', '3:2', '3:4', '4:3', '9:16', '16:9', '21:9'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'PIX_IMAGE_2',
    name: 'PIX Image 2',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 16,
    },
    params: [
      {
        name: 'quality',
        type: 'string',
        defaultValue: 'medium',
        options: ['low', 'medium', 'high'],
      },
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '1K',
        options: ['1K', '2K', '4K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: 'auto',
        options: [
          '1:1',
          '2:3',
          '3:2',
          '3:4',
          '4:3',
          '4:5',
          '5:4',
          '9:16',
          '16:9',
          '9:21',
          '21:9',
        ],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'PIX_NANO_PRO',
    name: 'PixNano Pro',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 14,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '2K',
        options: ['1K', '2K', '4K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '',
        options: [
          '',
          '1:1',
          '2:3',
          '3:2',
          '3:4',
          '4:3',
          '4:5',
          '5:4',
          '9:16',
          '16:9',
          '21:9',
        ],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'PIX_NANO_2',
    name: 'PixNano 2',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 14,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '2K',
        options: ['1K', '2K', '4K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '',
        options: [
          '',
          '1:1',
          '1:4',
          '1:8',
          '2:3',
          '3:2',
          '3:4',
          '4:1',
          '4:3',
          '4:5',
          '5:4',
          '8:1',
          '9:16',
          '16:9',
          '21:9',
        ],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'MIDJOURNEY_V8_2',
    name: '悠船 V8.2',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 20,
    },
    params: [
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '1:1',
        options: [
          '1:1',
          '2:3',
          '3:2',
          '3:4',
          '4:3',
          '16:9',
          '9:16',
          '21:9',
          '9:21',
        ],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '4',
        options: ['4'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'MIDJOURNEY_V8_1',
    name: '悠船 V8.1',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 20,
    },
    params: [
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '1:1',
        options: [
          '1:1',
          '2:3',
          '3:2',
          '3:4',
          '4:3',
          '16:9',
          '9:16',
          '21:9',
          '9:21',
        ],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'MIDJOURNEY',
    name: '悠船 V7',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 20,
    },
    params: [
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '1:1',
        options: [
          '1:1',
          '2:3',
          '3:2',
          '3:4',
          '4:3',
          '16:9',
          '9:16',
          '21:9',
          '9:21',
        ],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'MIDJOURNEY_NIJI_7',
    name: '悠船 Niji V7',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 20,
    },
    params: [
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '1:1',
        options: [
          '1:1',
          '2:3',
          '3:2',
          '3:4',
          '4:3',
          '16:9',
          '9:16',
          '21:9',
          '9:21',
        ],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'JIMENG_5_LITE',
    name: 'Doubao Seedream 5.0 Lite',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 14,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '2K',
        options: ['2K', '3K', '4K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '1:1',
        options: ['1:1', '2:3', '3:2', '3:4', '4:3', '9:16', '16:9', '21:9'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'DOUBAO_SEEDREAM_4_5',
    name: 'Doubao Seedream 4.5',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 14,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '2K',
        options: ['2K', '4K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '1:1',
        options: ['1:1', '2:3', '3:2', '3:4', '4:3', '9:16', '16:9', '21:9'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'QWEN_IMAGE_EDIT_MAX',
    name: 'Qwen Image Edit Max',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 3,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '1K',
        options: ['1K', '2K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '',
        options: [
          '',
          '1:1',
          '2:3',
          '3:2',
          '3:4',
          '4:3',
          '9:16',
          '16:9',
          '21:9',
        ],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '3', '4'],
      },
      {
        name: 'promptExtend',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'MINIMAX_IMAGE_01',
    name: 'MiniMax Image 01',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
    },
    params: [
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '1:1',
        options: ['1:1', '16:9', '4:3', '3:2', '2:3', '3:4', '9:16', '21:9'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4', '9'],
      },
    ],
    referModes: [],
    promptDefault: 'null',
  },
  {
    code: 'QWEN_IMAGE_EDIT_PLUS',
    name: 'Qwen Image Edit Plus',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
      image: 3,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '1K',
        options: ['1K', '2K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '',
        options: [
          '',
          '1:1',
          '2:3',
          '3:2',
          '3:4',
          '4:3',
          '9:16',
          '16:9',
          '21:9',
        ],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '3', '4'],
      },
      {
        name: 'promptExtend',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'MINIMAX_IMAGE_01_LIVE',
    name: 'MiniMax Image 01 Live',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      text: 20,
    },
    params: [
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '1:1',
        options: ['1:1', '16:9', '4:3', '3:2', '2:3', '3:4', '9:16'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4', '9'],
      },
      {
        name: 'styleType',
        type: 'string',
        defaultValue: '',
        options: ['', '漫画', '元气', '中世纪', '水彩'],
      },
    ],
    referModes: [],
    promptDefault: 'null',
  },
  {
    code: 'IMAGE_UPSCALE',
    name: 'Image Upscale',
    nodeType: 'GENERATE_IMAGE',
    maxInputs: {
      image: 1,
    },
    params: [
      {
        name: 'superResolutionType',
        type: 'string',
        defaultValue: 'ultra',
        options: ['super', 'ultra'],
      },
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '1080P',
        options: ['1080P', '2K', '4K'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
  {
    code: 'SEEDANCE_2_5',
    name: 'Seedance 2.5',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 30,
      video: 10,
      audio: 10,
      mediaTotal: 50,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['480P', '720P', '1080P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: 'adaptive',
        options: ['adaptive', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        min: 4,
        max: 30,
        step: 1,
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'referToVideo',
        options: [
          'textToVideo',
          'referToVideo',
          'imageToVideo',
          'firstAndLastFrame',
          'videoEdit',
          'videoExtend',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'outputFormat',
        type: 'string',
        defaultValue: 'mp4',
        options: ['mp4', 'mov'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'referToVideo',
        requirement:
          '图片、视频、音频合计必须为 1～50 个（30张图+10段视频+10段音频）',
      },
      {
        value: 'imageToVideo',
        requirement: '图片有且仅有 1 个（需要将aspectRatio 置为 adaptive ）',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个 （需要将aspectRatio 置为 adaptive ）',
      },
      {
        value: 'videoEdit',
        requirement:
          '视频必须为 1 个 （需要将duration 置为 -1 ，aspectRatio 置为 adaptive ）',
      },
      {
        value: 'videoExtend',
        requirement: '视频必须为 1 个 （需要将aspectRatio 置为 adaptive ）',
      },
    ],
    promptDefault:
      '保持无字幕，避免生成任何文字或字幕，不要生成 logo，不要生成水印。',
  },
  {
    code: 'SEEDANCE_2_0',
    name: 'Seedance 2.0',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 9,
      video: 3,
      audio: 3,
      mediaTotal: 15,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: [
          '480P',
          '720P',
          '1080P',
          '4K',
          'SUPER_720P',
          'SUPER_1080P',
          'SUPER_4K',
        ],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: [
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'referToVideo',
        options: [
          'textToVideo',
          'referToVideo',
          'imageToVideo',
          'firstAndLastFrame',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'bitrateMode',
        type: 'string',
        defaultValue: 'standard',
        options: ['standard', 'high'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'referToVideo',
        requirement: '图片、视频、音频合计必须为 1～15 个',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
    ],
    promptDefault:
      '保持无字幕，避免生成任何文字或字幕，不要生成 logo，不要生成水印。',
  },
  {
    code: 'SEEDANCE_2_0_FAST',
    name: 'Seedance 2.0 Fast',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 9,
      video: 3,
      audio: 3,
      mediaTotal: 15,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['480P', '720P', 'SUPER_720P', 'SUPER_1080P', 'SUPER_4K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: [
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'referToVideo',
        options: [
          'textToVideo',
          'referToVideo',
          'imageToVideo',
          'firstAndLastFrame',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'bitrateMode',
        type: 'string',
        defaultValue: 'standard',
        options: ['standard', 'high'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'referToVideo',
        requirement: '图片、视频、音频合计必须为 1～15 个',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
    ],
    promptDefault:
      '保持无字幕，避免生成任何文字或字幕，不要生成 logo，不要生成水印。',
  },
  {
    code: 'SEEDANCE_2_0_MINI',
    name: 'Seedance 2.0 Mini',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 9,
      video: 3,
      audio: 3,
      mediaTotal: 15,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['480P', '720P', 'SUPER_720P', 'SUPER_1080P', 'SUPER_4K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: [
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'referToVideo',
        options: [
          'textToVideo',
          'referToVideo',
          'imageToVideo',
          'firstAndLastFrame',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'bitrateMode',
        type: 'string',
        defaultValue: 'standard',
        options: ['standard', 'high'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'referToVideo',
        requirement: '图片、视频、音频合计必须为 1～15 个',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
    ],
    promptDefault:
      '保持无字幕，避免生成任何文字或字幕，不要生成 logo，不要生成水印。',
  },
  {
    code: 'WAN3_0',
    name: 'Wan 3.0',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 10,
      video: 5,
      audio: 5,
      mediaTotal: 20,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['1080P', '720P', '480P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: 'adaptive',
        options: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: [
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
          '16',
          '17',
          '18',
          '19',
          '20',
          '21',
          '22',
          '23',
          '24',
          '25',
          '26',
          '27',
          '28',
          '29',
          '30',
        ],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'referToVideo',
        options: [
          'textToVideo',
          'referToVideo',
          'imageToVideo',
          'firstAndLastFrame',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'promptExtend',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'referToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'WAN3_0_PRIME',
    name: 'Wan 3.0 Prime',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 10,
      video: 5,
      audio: 5,
      mediaTotal: 20,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['1080P', '720P', '480P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: 'adaptive',
        options: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: [
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
          '16',
          '17',
          '18',
          '19',
          '20',
          '21',
          '22',
          '23',
          '24',
          '25',
          '26',
          '27',
          '28',
          '29',
          '30',
        ],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'referToVideo',
        options: [
          'textToVideo',
          'referToVideo',
          'imageToVideo',
          'firstAndLastFrame',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'promptExtend',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'referToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
    ],
    promptDefault: 'null',
  },
  {
    code: 'MINIMAX_H3',
    name: 'MiniMax H3',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 9,
      video: 3,
      audio: 3,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '2K',
        options: ['768P', '2K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: 'adaptive',
        options: ['adaptive', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: ['5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'textToVideo',
        options: [
          'textToVideo',
          'referToVideo',
          'imageToVideo',
          'firstAndLastFrame',
          'lastFrameToVideo',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'referToVideo',
        requirement: '图片、视频必须为 1～12 个',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
      {
        value: 'lastFrameToVideo',
        requirement: '图片必须为 1 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'MINIMAX_H3_MAX',
    name: 'MiniMax H3 Max',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 2,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '768P',
        options: ['480P', '768P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: ['5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'textToVideo',
        options: ['textToVideo', 'imageToVideo', 'firstAndLastFrame'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
    ],
    promptDefault: 'null',
  },
  {
    code: 'VIDU_Q3_PRO',
    name: 'Vidu Q3 Pro',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 7,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['720P', '1080P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['', '16:9', '9:16', '4:3', '3:4', '1:1'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
          '16',
        ],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'textToVideo',
        options: [
          'textToVideo',
          'imageToVideo',
          'firstAndLastFrame',
          'imageRefer',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
      {
        value: 'imageRefer',
        requirement: '图片必须为 1～3 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'VIDU_Q3_MIX',
    name: 'Vidu Q3 Mix',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 3,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['720P', '1080P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['', '16:9', '9:16', '4:3', '3:4', '1:1'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: [
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
          '16',
        ],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'imageRefer',
        options: ['imageRefer'],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'imageRefer',
        requirement: '图片必须为 1～3 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'VIDU_Q2_PRO',
    name: 'Vidu Q2 Pro',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 7,
      video: 2,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['720P', '1080P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['', '16:9', '9:16', '4:3', '3:4', '1:1'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '0'],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'referToVideo',
        options: [
          'referToVideo',
          'imageToVideo',
          'firstAndLastFrame',
          'imageRefer',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'referToVideo',
        requirement: '视频必须为 1～2 个',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
      {
        value: 'imageRefer',
        requirement: '图片必须为 1～7 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'HAPPYHORSE_11',
    name: 'HappyHorse 1.1',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 9,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '1080P',
        options: ['720P', '1080P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '',
        options: [
          '',
          '16:9',
          '9:16',
          '1:1',
          '4:3',
          '3:4',
          '4:5',
          '5:4',
          '9:21',
          '21:9',
        ],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: ['3', '5', '10', '15'],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'textToVideo',
        options: ['textToVideo', 'imageToVideo', 'referToVideo'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'referToVideo',
        requirement: '图片必须为 1～9 个',
      },
    ],
    promptDefault: 'null',
  },
  {
    code: 'SEEDANCE_1_5',
    name: 'Seedance 1.5 Pro',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 2,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['480P', '720P', '1080P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['', '16:9', '9:16', '4:3', '3:4', '1:1', '21:9'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: ['4', '5', '6', '7', '8', '9', '10', '11', '12'],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'textToVideo',
        options: ['textToVideo', 'imageToVideo', 'firstAndLastFrame'],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'HAPPYHORSE_10',
    name: 'HappyHorse 1.0',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 9,
      video: 1,
      audio: 1,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['720P', '1080P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '',
        options: ['', '16:9', '9:16', '1:1', '4:3', '3:4'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: ['3', '5', '10', '15'],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'textToVideo',
        options: ['textToVideo', 'imageToVideo', 'referToVideo', 'videoEdit'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'referToVideo',
        requirement: '图片必须为 1～9 个',
      },
      {
        value: 'videoEdit',
        requirement: '视频必须为 1 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'KLING_V3_OMNI',
    name: 'Kling V3 Omni',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 14,
      video: 10,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['720P', '1080P', '4K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['', '16:9', '9:16', '1:1'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: [
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'referToVideo',
        options: [
          'textToVideo',
          'referToVideo',
          'imageToVideo',
          'firstAndLastFrame',
          'imageRefer',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'referToVideo',
        requirement: '视频必须为 1 个',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
      {
        value: 'imageRefer',
        requirement: '图片必须为 1～7 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'KLING_V3',
    name: 'Kling V3',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 2,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['720P', '1080P', '4K'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['', '16:9', '9:16', '1:1'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: [
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'textToVideo',
        options: ['textToVideo', 'imageToVideo', 'firstAndLastFrame'],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'false',
        options: ['true', 'false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'KLING_O1',
    name: 'Kling O1',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 7,
      video: 1,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['720P', '1080P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['', '16:9', '9:16', '1:1'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: ['5', '10'],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'referToVideo',
        options: [
          'textToVideo',
          'referToVideo',
          'imageToVideo',
          'firstAndLastFrame',
          'imageRefer',
          'videoEdit',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'referToVideo',
        requirement: '视频必须为 1 个',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
      {
        value: 'imageRefer',
        requirement: '图片必须为 1～7 个',
      },
      {
        value: 'videoEdit',
        requirement: '视频必须为 1 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'KLING_2_6',
    name: 'Kling 2.6',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 2,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '1080P',
        options: ['720P', '1080P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['', '16:9', '9:16', '1:1'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: ['5', '10'],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'textToVideo',
        options: ['textToVideo', 'imageToVideo', 'firstAndLastFrame'],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'PIXVERSE_V6',
    name: 'PixVerse V6',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 2,
      video: 1,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['360P', '540P', '720P', '1080P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['16:9', '4:3', '1:1', '3:4', '9:16', '2:3', '3:2', '21:9'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: ['5', '8', '10', '15'],
      },
      {
        name: 'extendDuration',
        type: 'string',
        defaultValue: '5',
        options: ['5', '8', '10', '15'],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'textToVideo',
        options: [
          'textToVideo',
          'imageToVideo',
          'firstAndLastFrame',
          'videoExtend',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
      {
        value: 'videoExtend',
        requirement: '视频必须为 1 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'PIXVERSE_C1',
    name: 'PixVerse C1',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 3,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '720P',
        options: ['360P', '540P', '720P', '1080P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['16:9', '4:3', '1:1', '3:4', '9:16', '2:3', '3:2', '21:9'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: ['5', '8', '10', '15'],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'textToVideo',
        options: [
          'textToVideo',
          'imageToVideo',
          'firstAndLastFrame',
          'referToVideo',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
      {
        value: 'referToVideo',
        requirement: '图片必须为 1～3 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'HAILUO_23',
    name: 'Hailuo 2.3',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 3,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '768P',
        options: ['768P', '1080P'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '6',
        options: ['6', '10'],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'textToVideo',
        options: ['textToVideo', 'imageToVideo'],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'false',
        options: ['false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'HAILUO_02',
    name: 'Hailuo 02',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      image: 3,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '768P',
        options: ['768P', '1080P'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '6',
        options: ['6', '10'],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'textToVideo',
        options: [
          'textToVideo',
          'imageToVideo',
          'lastFrameToVideo',
          'firstAndLastFrame',
        ],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'false',
        options: ['false'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'lastFrameToVideo',
        requirement: '图片必须为 1 个',
      },
      {
        value: 'firstAndLastFrame',
        requirement: '图片必须为 2 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'WAN2_6',
    name: 'Wan 2.6',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      text: 20,
      audio: 1,
      image: 5,
      video: 3,
      mediaTotal: 5,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '1080P',
        options: ['720P', '1080P'],
      },
      {
        name: 'aspectRatio',
        type: 'string',
        defaultValue: '16:9',
        options: ['', '16:9', '9:16', '1:1', '4:3', '3:4'],
      },
      {
        name: 'duration',
        type: 'string',
        defaultValue: '5',
        options: [
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '8',
          '9',
          '10',
          '11',
          '12',
          '13',
          '14',
          '15',
        ],
      },
      {
        name: 'referModel',
        type: 'string',
        defaultValue: 'referToVideo',
        options: ['textToVideo', 'referToVideo', 'imageToVideo'],
      },
      {
        name: 'includeAudio',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true'],
      },
      {
        name: 'promptExtend',
        type: 'boolean',
        defaultValue: 'true',
        options: ['true', 'false'],
      },
      {
        name: 'multiShot',
        type: 'boolean',
        defaultValue: 'false',
        options: ['false', 'true'],
      },
      {
        name: 'count',
        type: 'int',
        defaultValue: '1',
        options: ['1', '2', '4'],
      },
    ],
    referModes: [
      {
        value: 'textToVideo',
        requirement: '无需输入素材',
      },
      {
        value: 'referToVideo',
        requirement: '图片、视频必须为 1～5 个',
      },
      {
        value: 'imageToVideo',
        requirement: '图片必须为 1 个',
      },
    ],
    promptDefault: '',
  },
  {
    code: 'VIDEO_UPSCALE',
    name: 'Video Upscale',
    nodeType: 'GENERATE_VIDEO',
    maxInputs: {
      video: 1,
    },
    params: [
      {
        name: 'resolution',
        type: 'string',
        defaultValue: '1080P',
        options: ['1080P', '2K', '4K'],
      },
      {
        name: 'frameRate',
        type: 'string',
        defaultValue: '',
        options: ['', '30FPS', '60FPS'],
      },
    ],
    referModes: [],
    promptDefault: '',
  },
];
